### ISSUE TITLE
Bindings broken after scene reload

### ISSUE THREAD

**Issue by onelivesleft** [ValveSoftware/steamvr_unity_plugin#216]
After reloading our game scene the VR interaction breaks down; it seems to lose all actions. First error:
```
GetOriginTrackedDeviceInfo error (/actions/default/in/Pose): InvalidHandle handle: 1152934664386642276 activeOrigin: 2305856168993489310 active: True
```
After which performance goes to hell and VR controls no longer work, as every tick it spits out another exception, seemingly for each action. is there some call I need to make after reloading the scene to reconnect or regenerate the VR bindings?

![image](https://user-images.githubusercontent.com/17881109/49253877-996cad80-f41f-11e8-92cb-77c6f7439d78.png)

**Comment by zite** [comment]
Can you try and reproduce this with the latest beta version of the plugin? I think it may be fixed there: https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.1.5

**Comment by onelivesleft** [comment]
I just tried again with my current setup and couldn't reproduce it.  This is odd: it wasn't just a one-off thing, it happened every time.  I guess I had something setup wrong before, and after working with the bindings for a while it has ironed itself out?  If it recurs I'll try the beta and post back.

**Comment by onelivesleft** [comment]
This is happening again; unsure at what point it started.  As per your suggestion above I've tried upgrading to 2.1.5, which did not fix it.

**Comment by zite** [comment]
Is your [SteamVR] object still in the scene after reload? Did you try with 2.1.5 or 2.2 which is the latest beta?

**Comment by onelivesleft** [comment]
I hadn't tried 2.2 but I've upgraded to it now; issue persists.  As far as I can tell the `[VR]` object (root object containing `[CameraRig]` and `[Static]`) is destroyed as the scene closes and created again after; it's definitely present in the new scene, and I added a script to it which writes to the log in `OnDestroy`; that output is present.

**Comment by zite** [comment]
Ok, I'll look into this more on monday. So to be clear you're reloading a scene, and don't have the [SteamVR] object marked as DoNotDestroy. Or are you loading a different scene?

**Comment by onelivesleft** [comment]
Reloading the one scene.  I can't find anywhere in our code marking it as DontDestroy, and it appears to me that it is indeed being destroyed. There's nothing VR related in the DontDestroyOnLoad root in the Hierarchy.

**Comment by zite** [comment]
I've tried this in the interaction system sample scene and ran into a small issue with the player getting duplicated, then after turning that off the RenderModel script throwing an error. I've fixed this but I don't think it was your problem as it didn't actually break anything, just complained. Can you reproduce this easily using just the plugin?

**Comment by zite** [comment]
The fixes I made are in RC2 here: https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.2RC2

**Comment by onelivesleft** [comment]
RC2 didn't fix it.  

I made a new project to test with, and added RC2 to it, then copied my `actions.json` over from the game into the test project.  Used 'Save and generate` in the SteanVR Input panel, then tried to set bindings by going to `Open binding UI` -> Create binding.  I attached all the mandatory actions and hit replace default bindings... this didn't work. I end up in some weird Legacy mode:

![image](https://user-images.githubusercontent.com/17881109/51628049-e199df00-1f3b-11e9-8660-0a448824f4c4.png)

I don't know if this is a bug or something odd with my `actions.json` file.  Here it is (renamed to .txt so git would take it):
[actions.json.txt](https://github.com/ValveSoftware/steamvr_unity_plugin/files/2788626/actions.json.txt)

**Comment by zite** [comment]
I'm going to guess it's the actions that start with an underscore causing issues. Can you try changing those?

**Comment by onelivesleft** [comment]
Changing them so they no longer start with an underscore didn't make any difference, to either situation.

**Comment by onelivesleft** [comment]
It fixed the legacy binding issue, but not the original problem.

**Comment by zite** [comment]
can you search your scene for the SteamVR_Behaviour component? Does that get destroyed when you're reloading the scene?

**Comment by onelivesleft** [comment]
I added a check for this to the start of our VR startup routine:

```csharp
IEnumerator Start() {
    StartCoroutine(CheckForSteamVRBehaviour());
    
    VRSettings.LoadDeviceByName("OpenVR");
    yield return null;
    VRSettings.enabled = true;
    VRgameObject.SetActive(true);
    SteamVR.settings.pauseGameWhenDashboardVisible = false;
}

IEnumerator CheckForSteamVRBehaviour()
{
    int tick = -1;
    SteamVR_Behaviour behaviour = null;
    while (behaviour == null)
    {
        tick++;
        behaviour = FindObjectOfType<SteamVR_Behaviour>();
        yield return null;
    }
    Debug.Log("Found SteamVR_Behaviour on tick " + tick);
    // DontDestroyOnLoad(behaviour.gameObject);
}
```

Ran as above, it finds the `SteamVR_Behaviour` object on tick 2, and when I reload the scene it finds it on tick 2 again.  I tried setting `DontDestroyOnLoad` by uncommenting the line, after which it found it initially on tick 2, and after reload on tick 0.  So: it looks to me like it's normally being destroyed and recreated on reload.

I tried setting its `doNotDestroy` flag to `false`; it was still found on reload at tick 2.

**Comment by zite** [comment]
Try using `SteamVR.Initialize(true);` to enable openvr instead of your method. Check out the SteamVR_ForceSteamVRMode.cs script for an example

**Comment by onelivesleft** [comment]
Success! That seems to have done the job.  Thanks for the assistance; if you need me to test some more (if you want to get `LoadDeviceByName` working for instance) let me know.

**Comment by zite** [comment]
Great! Will let you know.
