### ISSUE TITLE
Freeze when returning from SteamVR system menu

### ISSUE THREAD

**Issue by onelivesleft** [ValveSoftware/steamvr_unity_plugin#221]
Symptoms:
I activate the steamvr system menu then try to return to game: in VR I hang in the lobby forever, because Unity.exe itself has locked up; the process must be killed.

Cause:
This seems to be caused by the `SteamVR_Render` script which is automatically genererated with the `[SteamVR]` root object; running the game, disabling that script, and then going to system menu no longer causes the hang.

My Fix:
For now I'm simply disabling this script as soon as it appears.  

Other info:
I'm not 100%, but I think that on one attempt at tracking this down I set a break point in the init process, and upon resuming the bug did not manifest even with the component active.  Perhaps the delay during init prevented a timing bug?  However, I couldn't recreate this behaviour.

**Comment by zite** [comment]
Thanks for the report, could I get some more information from you? Which version of SteamVR are you running? Which hmd? And what version of Unity?

**Comment by onelivesleft** [comment]
Unity: 5.6.6f2
SteamVR Plugin: 2.0.1
SteamVR: 1.1.3
OS: Win 10 64-bit
Vive standard.

**Comment by zite** [comment]
Thanks, found the issue. I'll get this fixed in the next beta update. I'll leave this open until then.

**Comment by AJCMPC** [comment]
The release of SteamVR 1.1.3 on 11/27/2018 introduced a breaking change to a VR experience we have in flight at multiple retail locations. We patched it as best we could, but we are still unsure of the correct solution.

The release of 1.1.3 broke the SteamVR_LoadLevel script. That script now causes the renderer to hang indefinitely and even crash the operating system any time we try to use it to load a level. We suspect this is related to the same bug discussed above.

We have tested on:
Unity 2018.2
SteamVR 1.1.3
SteamVR Unity Plugin v2.0.1
OS: Win 10 64-bit

We are not able to control scene transitions until this patch is released. We are forced to push the user out to the SteamVR Home environment every time we need to load a new level. Can you confirm when the fix for this bug will be released?

Also, is there a deprecation schedule for SteamVR? If integral scripts like SteamVR_LoadLevel are deprecated (not sure if that is the intent), we would very much appreciate a warning.

**Comment by zite** [comment]
Can you verify if this is still an issue with the latest SteamVR beta?

**Comment by onelivesleft** [comment]
Can do so tomorrow

**Comment by onelivesleft** [comment]
Sorry for delay; procrastination is a helluva drug.  This seems to be OK now.
However, since I'm also experiencing #216 under the same conditions I can't confirm 100%, as that issue might be screwing things up before the point this one would cause a hang; unlikely to be the case, but pessimally possible.

**Comment by zite** [comment]
Thanks for the retest. New issue, same result. I've fixed this in a version I just uploaded. It's named the same, but just download the 2.2rc1 unitypackage again and it should be fixed.

If you're curious the fix is here: https://github.com/ValveSoftware/steamvr_unity_plugin/blob/beta/Assets/SteamVR/InteractionSystem/Core/Scripts/Hand.cs#L562

**Comment by onelivesleft** [comment]
Thanks for helping with this.  RC1 did not fix the issue, however on investigating what exactly in `SteamVR_Render` was triggering the hang I found it to be when `OnInputFocus` sets `Time.timeScale` to 0: our game really does not like this!

Since its a network game we never want to pause like this, so I'm now setting `SteamVR.settings.pauseGameWhenDashboardVisible = false;` after initializing VR, and so far this seems to clear up the issue, without disabling the entire `SteamVR_Render` script.

When debugging this I could make the game recover by using the Immediate Window to reset `Time.timeScale` to 1, as the `OnInputFocus` event should do when you return to the game.  However, I don't think it failing to do so is a SteamVR problem; I believe somewhere else in our code is blocking the event system by busylooping or something similar when the `timeScale` is 0.  My hunch is it's in the "cInput" asset (in case someone else reports something similar in future).  Again: thanks!

**Comment by bddckr** [comment]
>I believe somewhere else in our code is blocking the event system

I don't think it's your end at all. The SteamVR plugin currently only polls for OpenVR events in `Update` which won't be run by Unity when the time scale is set to 0:
https://github.com/ValveSoftware/steamvr_unity_plugin/blob/fec2de6c5902ad07f21af2be8258a794dbb77b77/Assets/SteamVR/Scripts/SteamVR_Render.cs#L357-L391

I think an alternative would be to move this into a (cancelable!) coroutine which only gives issues when the game object the component is on is turned off (this is how Unity behaves regarding automatic coroutine stops). While we're on that note perhaps the result of `Marshal.SizeOf` can be cached, too 😄

**Comment by bddckr** [comment]
Turns out I'm wrong here: Unity only stops calling `FixedUpdate` - whoops!

**Comment by zite** [comment]
The hang has been fixed and hands are not meant to be updated while the dashboard is up. Closing this issue
