### ISSUE TITLE
SteamVR uses legacy bindings on first startup of game and not the bindings that shipped with the game.

### ISSUE THREAD

**Issue by Kulgann** [ValveSoftware/steamvr_unity_plugin#885]
This only happens when the game is installed trough steam. Running in the editor and from the local build is fine. For most users of our game a simple restart fixes the issue and game recognizes the proper bindings and works. However for some this does not work. What can I do to fix this ?  I'm using the SteamVR Unity Plugin 2.6.1(skd 1.13.10)

**Comment by zite** [comment]
This could be a issue with the app key in the binding files. You can try removing the app_key line from the actions.json and bindings json files and see if that fixes the issue. The next version of the plugin will fix this.

**Comment by zite** [comment]
The version that should fix this is out now: https://github.com/ValveSoftware/steamvr_unity_plugin/releases/tag/2.7.1

**Comment by Kulgann** [comment]
I upgraded to the 2.7.1 release and the issue still persists. In the steam vr settings I have set the app key to  steam.app.[ourAppId]. We tried a fresh install by deleting all game files and steam user settings. Installing the game results in the legacy bindings being used. Running the game a second time results in the correct default bindings (the ones we created and ship with the game) being loaded. I also tested by deleting the app key line from the generated json files, the result was the same.

**Comment by IDLYA-David** [comment]
We also have this issue. Through viveport though not steam store.

**Comment by Kulgann** [comment]
> We also have this issue. Through viveport though not steam store.

Yes, we are also having the problem in viewport and any other platform that relies on SteamVR. If a fix is not comming a temp workaround would be nice.

**Comment by Kulgann** [comment]
Any info on this? We would really like to get this sorted asap.

**Comment by zite** [comment]
I'm not sure I understand the issue. Can you list clear repro steps or upload an example project?

**Comment by Kulgann** [comment]
> Does deleting the app key line from the JSON not fix the issue?

No it does not.

**Comment by zite** [comment]
Can you send me a simple project that reproduces the issue? Or link me to one?
