### ISSUE TITLE
Bindings Not Saving

### ISSUE THREAD

**Issue by ACaves** [ValveSoftware/steamvr_unity_plugin#921]
Hey guys i just updated Steam VR as of 25 Feb 2021 and none of my bindings are able to be saved and used in Unity. Anyone got any ideas on how i fix it?

**Comment by zite** [comment]
Are you seeing any errors in the binding UI or in unity?

**Comment by Mouledoux** [comment]
Same issue, no errors, the binding DOES get saved to Documents>steamvr>input
but SteamVR wont apply it as the active binding, nor does it display the actions correctly (some of them are capitalized, others are not)

**Comment by zite** [comment]
Do you have something else set as the active binding?

**Comment by Mouledoux** [comment]
It doesn't matter
Default doesn't work, and custom is never saved
It is the only custom binding in all of steamvr>input
It DOES seem to be reading the proper action.json, because the binding ui shoes the proper localization tags
but it doesn't save after rebinding. It just reverts to the "vive_controller" "These are the official bindings..."

**Comment by zite** [comment]
What version of SteamVR are you using @Mouledoux?

**Comment by RicardoVRTom** [comment]
I'm also seeing what I think is the same issue. When I open the bindings UI in Unity select Vive Tracker on Waist, there is no default/current binding for the controller. I have tried this with on left foot and on right foot as well.

I try to create a new binding, set the pose component etc, ask it to replace the default binding, close the bindings window, hit save and generate and it is saved in streamingAssets as applciation_generated... 

If I then go back to the bindings window, there is no current or default binding set. This seems to mean that the tracker does not work with the behaviour pose script, as the transform is not moving when I try to setup a tracker in Unity.

I'm running 1.13.9 for the SteamVR client & 2.7.3 for the Unity Plugin. Usually I run SteamVR without Steam running as I am an enterprise user, however I did jump through the hoops to try setting bindings with Steam open as well, and still nothing. I'm also not getting any errors in the console.

**Comment by Mouledoux** [comment]
My issue was resolved in #947
Updating to SteamVR 1.16.[something] fixed the no input from the controllers.
I haven't tested saving the profiles again, but the machine I was testing on may have had certain read/write privileges that was preventing steam from saving the profiles.

**Comment by RicardoVRTom** [comment]
Interesting, thanks for the reply, I had just been doing some testing with SteamVR version 1.16.10. I am also still seeing issues with default bindings saving correctly, I did have this working with a previous version of SteamVR & the Unity plugin. So I don't think the read/write privileges you mention are the issue, or at least not in my case.
