### ISSUE TITLE
Unity 2020.3.2 crashes every other time

### ISSUE THREAD

**Issue by AndersMalmgren** [ValveSoftware/steamvr_unity_plugin#936]
We have migrated our game to 2020 LTS and we have a problem with that every other time the game crashes when played. Both in built and in editor. @zite have more info on this matter. But he said you have a problem when steamvr and Steamworks are used together.

We are on XR Plugin Management 4.0.1, SteamVR plugin 2.7.3 and OpenVR XR Plugin 1.1.4

**Comment by AndersMalmgren** [comment]
Some times it doesnt crash but start in some kind of theatre mode and the game exists

**Comment by zite** [comment]
We've been troubleshooting this offline. I believe this may have been fixed by later versions of things? Can you confirm where we're at with this @AndersMalmgren?

**Comment by AndersMalmgren** [comment]
@keithbradner I havent tried the game built in a while. Just tested and the bug is back. (2020.3.7). It doesnt happen every other time this time around though. I could start the game 2 times. The third time it started in Theater mode :/

After that it starts every other time correct and every other time Theatre mode and exists
