### ISSUE TITLE
Conflict with WaveVR SDK

### ISSUE THREAD

**Issue by Snorchy** [ValveSoftware/steamvr_unity_plugin#96]
If you have SteamVR plugin and WaveVR plugin (for Vive Focus) in the same project the console outputs namespace conflicts with ClickedEventArgs and ClickedEventHandler. These are the errors:

> Assets/WaveVR/Scripts/WaveVR_TrackedButtons.cs(15,15): error CS0101: The namespace global::' already contains a definition for ClickedEventArgs'

> Assets/WaveVR/Scripts/WaveVR_TrackedButtons.cs(22,22): error CS0101: The namespace global::' already contains a definition for ClickedEventHandler'

I'm a newbie in programming but I think this could be solved by properly namespacing every script in the plugin inside a generic namespace for SteamVR.

I did a very rough fix for my project but I don't know what naming conventions to use and propose here.

**Comment by zite** [comment]
Thanks for the feedback. I've fixed this in the most recent RC

**Comment by Mixchr** [comment]
Hi guys. I still get the issue? I have downloaded the recent steamVR plugin

**Comment by zite** [comment]
Ack sorry, looks like the Extras folder missed the namespacing pass. I'll get it in the next version, reopening for now.

**Comment by Mixchr** [comment]
Great thx!

**Comment by zite** [comment]
Actually it looks like while this is an issue in the mainline version of the plugin, it is fixed in the RC for verison 2.0. Those scripts have simply been removed. Check the releases section if you'd like to download the RC. I'll leave this issue open until I merge beta to main.
